municoes/urls.py
from django.urls import path
from .views import *

app_name = 'municoes'

urlpatterns = [
    path('logistica/readmunicao/', ReadMunicao.as_view(), name='readmunicao'),
    path('logistica/createmunicao/', CreateMunicao.as_view(), name='createmunicao'),
    path('logistica/updatemunicao/<int:pk>', UpdateMunicao.as_view(), name='updatemunicao'),
    path('logistica/createconsuno/', CreateConsumo.as_view(), name='createconsumo'),
]

sisgestao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    #path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    #path('militares/', include('militares.urls', namespace='militares')),
    #path('contatos/', include('contatos.urls', namespace='contatos')),
    #path('documentos/', include('documentos.urls', namespace='documentos')),
    #path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    #path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('operacoes/', include('operacoes.urls', namespace='operacoes')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('municoes/', include('municoes.urls', namespace='municoes')),
    path('armamentos/', include('armamentos.urls', namespace='armamentos')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

municoes/models.py
from django.db import models
from quarteis.models import Unidade, Subunidade

LISTA_MUN = (
    ("Mun 7,62mm Comum", "Mun 7,62mm Comum"),
    ("Mun 9mm", "Mun 9mm"),
    ("Mun 7,62mm Tr", "Mun 7,62mm Tr"),
    ("Mun .50", "Mun .50"),
    ("Mun 5,56mm", "Mun 5,56mm"),
    ("Mun Cal 12", "Mun Cal 12"),
    ("Mun menos letal", "Mun menos letal"),
    ("Gr menos letal", "Gr menos letal"),
    ("Mun 120mm", "Mun 120mm"),
    ("Mun 105mm", "Mun 105mm"),
    ("Mun 155mm", "Mun 155mm"),
    ("Outros", "Outros")
)


class Municao(models.Model):
    classificacao = models.CharField(
        max_length=50,
        choices=LISTA_MUN,
        default="Outros",
    )
    tipo = models.CharField(max_length=100)
    lote = models.CharField(max_length=20)
    quantidade = models.IntegerField(default=0)
    codigo_virola = models.CharField(max_length=20)
    vencimento = models.DateField(blank=True, null=True)
    unidade = models.ForeignKey(Unidade, related_name="municao", on_delete=models.PROTECT)

    def __str__(self):
        return self.tipo + ' - ' + self.lote + ' - ' + self.unidade.abreviatura


class ConsumoMun(models.Model):
    atividade = models.CharField(max_length=100)
    municao = models.ForeignKey(Municao, related_name="consumo", on_delete=models.CASCADE)
    quantidade = models.IntegerField("Munição Consumida", default=0)
    data = models.DateField(auto_now=True)

    def __str__(self):
        return self.atividade + ' - ' + self.municao.tipo + ' - ' + \
               self.municao.lote + ' - ' + self.municao.unidade.abreviatura

municoes/forms.py
from django.forms import ModelForm
from django import forms
from .models import Municao, ConsumoMun
from quarteis.models import Subunidade


class CreateMunicaoForm(ModelForm):
    class Meta:
        model = Municao
        exclude = ['unidade']


class UpdateMunicaoForm(ModelForm):
    class Meta:
        model = Municao
        exclude = ['unidade']


class CreateConsumoForm(ModelForm):
    class Meta:
        model = ConsumoMun
        exclude = ['municao']

municoes/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import TemplateView, FormView, UpdateView, DetailView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Municao, ConsumoMun
from .forms import CreateMunicaoForm, UpdateMunicaoForm, CreateConsumoForm


class ReadMunicao(LoginRequiredMixin, ListView):
    template_name = "readmunicao.html"
    model = Municao


class CreateMunicao(LoginRequiredMixin, CreateView):
    template_name = "createmunicao.html"
    form_class = CreateMunicaoForm

    def form_valid(self, form):
        unidade_logada = self.request.user.pessoa.militar.subunidade.esc_sup
        form.instance.unidade = unidade_logada
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('municoes:readmunicao')


class CreateConsumo(LoginRequiredMixin, CreateView):
    template_name = "createconsumo.html"
    model = ConsumoMun
    form_class = CreateConsumoForm

    def form_valid(self, form):
        id = int(self.request.GET.get("municao_id"))
        municao = Municao.objects.get(id=id)
        form.instance.municao = municao
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('municoes:readmunicao')


class UpdateMunicao(LoginRequiredMixin, UpdateView):
    template_name = "updatemunicao.html"
    form_class = UpdateMunicaoForm

    def get_success_url(self):
        return reverse('municoes:readmunicao')

municoes/templates/createconsumo.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Cadastrar Munição
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Cadastrar Consumo</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Cadastre o consumo da munição</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Cadastrar</button>
                <a href="{% url 'municoes:readmunicao' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

municoes/templates/createmunicao.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Cadastrar Munição
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Cadastrar Munição</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Cadastre uma nova munição</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Cadastrar</button>
                <a href="{% url 'municoes:readmunicao' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

municoes/templates/readmunicao.html
{% extends 'base.html' %}
{% block titulo %}
Munições
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Munições</span>
                </a>
            </header>
            <table class="table">
                <div class="text-end">
                    <a href="{% url 'municoes:createmunicao' %}">
                        <button type="button" class="btn btn-outline-info">Novo</button>
                    </a>
                    <br>
                    <br>
                </div>
                <thead>
                    <tr>
                        <th scope="col">Classificação</th>
                        <th scope="col">Tipo</th>
                        <th scope="col">Lote</th>
                        <th scope="col">Quantidade</th>
                        <th scope="col">Cód. Virola</th>
                        <th scope="col">Vencimento</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for municao in object_list %}
                    <tr>
                        <th scope="row">{{ municao.classificacao }}</th>
                        <td>{{ municao.tipo }}</td>
                        <td>{{ municao.lote }}</td>
                        <td>{{ municao.quantidade }}</td>
                        <td>{{ municao.codigo_virola }}</td>
                        <td>{{ municao.vencimento }}</td>
                        <td>
                            <form action="{% url 'municoes:createconsumo' %}" method="get">
                                {% csrf_token %}
                                <fieldset>
                                    <input type="hidden" name="municao_id" value="{{ municao.id }}">
                                    <button type="submit" class="btn btn-outline-warning"
                                            data-toggle="tooltip"
                                            data-placement="top"
                                            title="Registrar consumo">
                                        <i class="bi bi-activity"></i>
                                    </button>
                                </fieldset>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

municoes/templates/updatemunicao.html
{% extends 'base.html' %}
{% block titulo %}
Atualizar Municao
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Atualizar Munição</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Atualize Munição</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Atualizar</button>
                <a href="{% url 'municoes:readmunicao' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
{% include 'footer.html' %}
{% endblock %}