armamentos/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'armamentos'

urlpatterns = [
    path('logistica/', HomepageLog.as_view(), name='homepagelog'),
    path('logistica/readarmamento/', ReadArmamento.as_view(), name='readarmamento'),
    path('logistica/createarmamento/', CreateArmamento.as_view(), name='createarmamento'),
    path('logistica/updatearmamento/<int:pk>', UpdateArmamento.as_view(), name='updatearmamento'),
    re_path(r'^logistica/recolhimentoarmamento/(?P<id>\d+)/$', recolhimento_armamento, name='recolhimento_armamento'),
    re_path(r'^logistica/descargaarmamento/(?P<id>\d+)/$', descarga_armamento, name='descarga_armamento'),
    re_path(r'^logistica/disponibilizararmamento/(?P<id>\d+)/$', disponibilizar_armamento, name='disponibilizar_armamento'),
    path('logistica/createalteracao/', CreateAlteracao.as_view(), name='createalteracao'),
    path('logistica/createatividade/', CreateAtividade.as_view(), name='createatividade'),
    path('logistica/createmanutencao/', CreateManutencao.as_view(), name='createmanutencao'),
    path('logistica/detailarmamento/<int:pk>', DetailArmamento.as_view(), name='detailarmamento'),
]

municoes/urls.py
from django.urls import path
from .views import *

app_name = 'municoes'

urlpatterns = [
    path('logistica/readmunicao/', ReadMunicao.as_view(), name='readmunicao'),
    path('logistica/createmunicao/', CreateMunicao.as_view(), name='createmunicao'),
    path('logistica/updatemunicao/<int:pk>', UpdateMunicao.as_view(), name='updatemunicao'),
    path('logistica/createconsuno/', CreateConsumo.as_view(), name='createconsumo'),
]

operacoes/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'operacoes'

urlpatterns = [
    path('homeop/', ReadOperacoes.as_view(), name='homepageop'),
    path('pessoal/', ReadPessoal.as_view(), name='readpessoal'),
    path('<int:pk>/geral', ReadGeral.as_view(), name='readgeral'),
    path('planoembarquegeral/', ReadPlanoEmbarqueGeral.as_view(), name='readplanoembarquegeral'),
    path('<int:pk>/planoembarque', ReadPlanoEmbarque.as_view(), name='readplanoembarque'),
    path('<int:pk>/planoembarquevtr', ReadPlanoEmbarqueVtr.as_view(), name='readplanoembarquevtr'),
    path('<int:pk>/armtop', ReadArmtOp.as_view(), name='readarmtop'),
    path('<int:pk>/updatearma', UpdateArma.as_view(), name='updatearma'),
    path('<int:pk>/updatepassageiro', UpdatePassageiro.as_view(), name='updatepassageiro'),
    path('<int:pk>/updatemotorista', UpdateMotorista.as_view(), name='updatemotorista'),
    path('<int:pk>/updatechefe', UpdateChefe.as_view(), name='updatechefe'),
    path('<int:pk>/updateplembvtr', UpdatePlEmbVtr.as_view(), name='updateplembvtr'),
    path('<int:pk>/updateplanoembarque', UpdatePlanoEmbarque.as_view(), name='updateplanoembarque'),
    path('createoperacao/', CreateOperacao.as_view(), name='createoperacao'),
    path('createplanoembarque/', CreatePlanoEmbarque.as_view(), name='createplanoembarque'),
    path('createplembvtr/', CreatePlEmbVtr.as_view(), name='createplembvtr'),
    path('createorgao/', CreateOrgao.as_view(), name='createorgao'),
    path('createoperacional/', CreateOperacional.as_view(), name='createoperacional'),
    path('createchefe/', CreateChVtr.as_view(), name='createchefevtr'),
    path('createmotorista/', CreateMotoVtr.as_view(), name='createmotovtr'),
    path('createpassageiro/', CreatePassageiro.as_view(), name='createpassagvtr'),
    path('download-plemb-pdf/', PlanoEmbarquePdf.as_view(), name='download_plemb_pdf'),
    path('download-manemb-pdf/', ManifestoEmbarquePdf.as_view(), name='download_manemb_pdf'),
    path('download-armt-pdf/', ArmamentoPdf.as_view(), name='download_armt_pdf'),
    path('download-participantes-pdf/', ParticipantesPdf.as_view(), name='download_participantes_pdf'),
    re_path(r'^create_fz/(?P<id>\d+)$', create_fz, name='create_fz'),
    re_path(r'^create_pst/(?P<id>\d+)$', create_pst, name='create_pst'),
    re_path(r'^delete_orgao/(?P<id>\d+)/$', delete_orgao, name='delete_orgao'),
    re_path(r'^delete_operacional/(?P<id>\d+)/$', delete_operacional, name='delete_operacional'),
    re_path(r'^delete_chefe/(?P<id>\d+)/$', delete_chefe, name='delete_chefe'),
    re_path(r'^delete_motorista/(?P<id>\d+)/$', delete_motorista, name='delete_motorista'),
    re_path(r'^delete_passageiro/(?P<id>\d+)/$', delete_passageiro, name='delete_passageiro'),
    re_path(r'^delete_armt/(?P<id>\d+)/$', delete_armt, name='delete_armt'),
    re_path(r'^delete_plano_embarque_vtr/(?P<id>\d+)/$', delete_plano_embarque_vtr, name='delete_plano_embarque_vtr'),
    re_path(r'^delete_plano_embarque_/(?P<id>\d+)/$', delete_plano_embarque, name='delete_plano_embarque'),
    re_path(r'^update_mun_armt/(?P<id>\d+)/$', update_mun_armt, name='update_mun_armt'),
]

sisgestao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    #path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    #path('militares/', include('militares.urls', namespace='militares')),
    #path('contatos/', include('contatos.urls', namespace='contatos')),
    #path('documentos/', include('documentos.urls', namespace='documentos')),
    #path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    #path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('operacoes/', include('operacoes.urls', namespace='operacoes')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('municoes/', include('municoes.urls', namespace='municoes')),
    path('armamentos/', include('armamentos.urls', namespace='armamentos')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viaturas/urls.py
from django.urls import path
from .views import *

app_name = 'viaturas'


urlpatterns = [
    path('logistica/readviatura/', ReadViatura.as_view(), name='readviatura'),
    path('logistica/createviatura/', CreateViatura.as_view(), name='createviatura'),
    path('logistica/createvrfpneu/', CreateVrfPneu.as_view(), name='createvrfpneu'),
    path('logistica/createvrfoleo/', CreateVrfOleo.as_view(), name='createvrfoleo'),
    path('logistica/createvrffiltro/', CreateVrfFiltro.as_view(), name='createvrffiltro'),
    path('logistica/createvrfsit/', CreateVrfSit.as_view(), name='createvrfsit'),
    path('logistica/createferramental/', CreateFerramental.as_view(), name='createferramental'),
    path('logistica/createalteracao/', CreateAlteracao.as_view(), name='createalteracao'),
    path('logistica/detailviatura/<int:pk>', DetailViatura.as_view(), name='detailviatura'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block titulo %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% block head %}{% endblock %}
    <style rel="stylesheet" href="{% static 'css/sidebars.css' %}"></style>
</head>
    <body>
        <div class="container-fluid">
            {% block main %}{% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
                integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
                integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
                crossorigin="anonymous"></script>
        <script src="{% static 'js/sidebars.js' %}"></script>
    </body>
</html>

templates/footer.html
{% load static %}
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-body-secondary">© 2024 Company, Inc</p>

        <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
        </ul>
    </footer>
</div>

templates/sidebarlog.html
{% load static %}
<div class="d-flex flex-column flex-shrink-0 h-100 p-3 text-bg-dark" style="width: 100%;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'armamentos:readarmamento' %}" class="nav-link active" aria-current="page">
                Armamentos
            </a>
        </li>
        <li>
            <a href="{% url 'municoes:readmunicao' %}" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                Munições
            </a>
        </li>
        <li>
            <a href="{% url 'viaturas:readviatura' %}" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
                Viaturas
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                Outro
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
                Outro
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
           data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>Outros</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
    </div>
</div>

templates/sidebarop.html
{% load static %}
<div class="d-flex flex-column flex-shrink-0 h-100 p-3 text-bg-dark" style="width: 100%;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <div class="d-flex flex-column flex-shrink-0 h-100 p-3 text-bg-dark" style="width: 100%;">
        <ul class="nav nav-pills flex-column mb-auto">
        {% for operacao in operacoes %}
            <li class="nav-item">
                <a href="{% url 'operacoes:readgeral' operacao.id %}" class="nav-link text-white" aria-current="page">
                    {{ operacao.nome.upper }}
                </a>
            </li>
            <li>
                <a href="{% url 'operacoes:readpessoal' %}" class="nav-link text-white" aria-current="page">
                    PESSOAL
                </a>
            </li>
            <li>
                <form method="get" action="{% url 'operacoes:readplanoembarquegeral' %}">
                    {% csrf_token %}
                    <fieldset>
                        <input type="hidden" name="pk_atv" value="{{ operacao.id }}">
                        <button type="submit" class="nav-link text-white" aria-current="page">PLANO DE EMBARQUE</button>
                    </fieldset>
                </form>
            </li>
            <li>
                <a href="{% url 'operacoes:readarmtop' operacao.id %}" class="nav-link text-white" aria-current="page">
                    ARMAMENTO
                </a>
            </li>
            <hr>
        {% endfor %}
        </ul>
    </div>
</div>

templates/sidebarpessoal.html
{% load static %}
<div class="d-flex flex-column flex-shrink-0 h-100 p-3 text-bg-dark" style="width: 100%;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'quarteis:readquarteis' %}" class="nav-link active" aria-current="page">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-airplane" viewBox="0 0 16 16">
                    <path d="M6.428 1.151C6.708.591 7.213 0 8 0s1.292.592 1.572 1.151C9.861 1.73 10 2.431 10 3v3.691l5.17 2.585a1.5 1.5 0 0 1 .83 1.342V12a.5.5 0 0 1-.582.493l-5.507-.918-.375 2.253 1.318 1.318A.5.5 0 0 1 10.5 16h-5a.5.5 0 0 1-.354-.854l1.319-1.318-.376-2.253-5.507.918A.5.5 0 0 1 0 12v-1.382a1.5 1.5 0 0 1 .83-1.342L6 6.691V3c0-.568.14-1.271.428-1.849m.894.448C7.111 2.02 7 2.569 7 3v4a.5.5 0 0 1-.276.447l-5.448 2.724a.5.5 0 0 0-.276.447v.792l5.418-.903a.5.5 0 0 1 .575.41l.5 3a.5.5 0 0 1-.14.437L6.708 15h2.586l-.647-.646a.5.5 0 0 1-.14-.436l.5-3a.5.5 0 0 1 .576-.411L15 11.41v-.792a.5.5 0 0 0-.276-.447L9.276 7.447A.5.5 0 0 1 9 7V3c0-.432-.11-.979-.322-1.401C8.458 1.159 8.213 1 8 1s-.458.158-.678.599"/>
                </svg>
                Unidades
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                Dados Pessoais
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
                Dados militares
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                Outro
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
                Outro
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
           data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>Outros</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
    </div>
</div>

templates/topbar.html
{% load static %}

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'homepage' %}" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="#" class="nav-link px-2 text-white active">Pessoal</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Inteligência</a></li>
                <li><a href="{% url 'operacoes:homepageop' %}" class="nav-link px-2 text-white">Operações</a></li>
                <li><a href="{% url 'armamentos:homepagelog' %}" class="nav-link px-2 text-white">Logística</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-outline-light me-2">Login</button>
                <button type="button" class="btn btn-warning">Sign-up</button>
            </div>
        </div>
    </div>
</header>