armamentos/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'armamentos'

urlpatterns = [
    path('logistica/', HomepageLog.as_view(), name='homepagelog'),
    path('logistica/readarmamento/', ReadArmamento.as_view(), name='readarmamento'),
    path('logistica/createarmamento/', CreateArmamento.as_view(), name='createarmamento'),
    path('logistica/updatearmamento/<int:pk>', UpdateArmamento.as_view(), name='updatearmamento'),
    re_path(r'^logistica/recolhimentoarmamento/(?P<id>\d+)/$', recolhimento_armamento, name='recolhimento_armamento'),
    re_path(r'^logistica/descargaarmamento/(?P<id>\d+)/$', descarga_armamento, name='descarga_armamento'),
    re_path(r'^logistica/disponibilizararmamento/(?P<id>\d+)/$', disponibilizar_armamento, name='disponibilizar_armamento'),
    path('logistica/createalteracao/', CreateAlteracao.as_view(), name='createalteracao'),
    path('logistica/createatividade/', CreateAtividade.as_view(), name='createatividade'),
    path('logistica/createmanutencao/', CreateManutencao.as_view(), name='createmanutencao'),
    path('logistica/detailarmamento/<int:pk>', DetailArmamento.as_view(), name='detailarmamento'),
]

municoes/urls.py
from django.urls import path
from .views import *

app_name = 'municoes'

urlpatterns = [
    path('logistica/readmunicao/', ReadMunicao.as_view(), name='readmunicao'),
    path('logistica/createmunicao/', CreateMunicao.as_view(), name='createmunicao'),
    path('logistica/updatemunicao/<int:pk>', UpdateMunicao.as_view(), name='updatemunicao'),
    path('logistica/createconsuno/', CreateConsumo.as_view(), name='createconsumo'),
]

sisgestao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    #path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    #path('militares/', include('militares.urls', namespace='militares')),
    #path('contatos/', include('contatos.urls', namespace='contatos')),
    #path('documentos/', include('documentos.urls', namespace='documentos')),
    #path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    #path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('operacoes/', include('operacoes.urls', namespace='operacoes')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('municoes/', include('municoes.urls', namespace='municoes')),
    path('armamentos/', include('armamentos.urls', namespace='armamentos')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

armamentos/models.py
from django.db import models
from quarteis.models import Unidade, Subunidade
from militares.models import Militar

SITUACAO = (
    ("Disponível", "Disp"),
    ("Indisponível", "Insdisp"),
    ("Descarregado", "Descarregado"),
    ("Recolhido", "Recolhido"),
)

ESCALOES = (
    ("1º Escalão", "1º Escalão"),
    ("2º Escalão", "2º Escalão"),
    ("3º Escalão", "3º Escalão"),
    ("4º Escalão", "4º Escalão"),
)

LISTA_ARMT = (
    ("Fuzil 7,62mm", "Fuzil 7,62mm"),
    ("Fuzil 5,56mm", "Fuzil 5,56mm"),
    ("Pistola 9mm", "Pistola 9mm"),
    ("Metralhadora MAG", "Metralhadora MAG"),
    ("FAP", "FAP"),
    ("FAC", "FAC"),
    ("Metralhadora .50", "Metralhadora .50"),
    ("Fuzil 5,56mm", "Fuzil 5,56mm"),
    ("Espingarda 12", "Espingarda 12"),
    ("Morteiro Pesado 120mm", "Morteiro Pesado 120mm"),
    ("Obuseiro 105mm", "Obuseiro 105mm"),
    ("Obuseiro 155mm", "Obuseiro 155mm"),
    ("Faca", "Faca"),
    ("Outros", "Outros")
)


class Armamento(models.Model):
    classificacao = models.CharField(
        max_length=50,
        choices=LISTA_ARMT,
        default="Outros",
    )
    modelo = models.CharField(max_length=100, null=True, blank=True)
    calibre = models.CharField(max_length=100, null=True, blank=True)
    fabricante = models.CharField(max_length=100, null=True, blank=True)
    nr_serie = models.CharField("Número de série", max_length=50)
    qtde_tiros = models.IntegerField("Quantidade de tiros", default=0)
    situacao = models.CharField(
        max_length=20,
        choices=SITUACAO,
        default="Disponível",
    )
    outros_nr_serie = models.TextField(null=True, blank=True)
    historico = models.TextField(null=True, blank=True)
    aes = models.TextField("Acessórios e Sobressalentes", null=True, blank=True)
    subunidade = models.ForeignKey(Subunidade, related_name="armamento", on_delete=models.PROTECT)

    def __str__(self):
        return self.classificacao + ' - ' + self.modelo + ' - ' + self.nr_serie + ' - ' + self.subunidade.abreviatura


class Alteracao(models.Model):
    situacao = models.CharField(
        "Situação do Armamento",
        max_length=20,
        choices=SITUACAO,
        default="Disponível",
    )
    data = models.DateField(auto_now_add=True, null=True, blank=True)
    alteracao = models.TextField("Ocorrência observada", null=True, blank=True)
    is_active = models.BooleanField("Está vigente", default=True)
    armamento = models.ForeignKey(Armamento, related_name="alteracao", on_delete=models.CASCADE)

    def __str__(self):
        return self.alteracao + ' - ' + self.armamento.classificacao + ' - ' + \
               self.armamento.nr_serie + ' - ' + self.armamento.subunidade.abreviatura


class Atividade(models.Model):
    disparos = models.IntegerField("Disparos efetuados", default=0)
    data_inicio = models.DateField("Início da atividade", auto_now_add=True, null=True, blank=True)
    data_fim = models.DateField("Fim da atividade", null=True, blank=True)
    nome = models.CharField("Nome da atividade", max_length=100, null=True, blank=True)
    armamento = models.ForeignKey(Armamento, related_name="atividade", on_delete=models.CASCADE)
    atirador = models.ForeignKey(Militar, related_name="atividade", on_delete=models.PROTECT)

    def __str__(self):
        return self.armamento.classificacao + ' - ' + self.armamento.nr_serie + ' - ' + \
               self.nome + ' - ' + self.disparos


class Manutencao(models.Model):
    data = models.DateField(auto_now_add=True, null=True, blank=True)
    escalao = models.CharField(
        "Escalão da Manutenção",
        max_length=20,
        choices=ESCALOES,
        default="1º Escalão",
    )
    armamento = models.ForeignKey(Armamento, related_name="manutencao", on_delete=models.CASCADE)

    def __str__(self):
        return (self.armamento.classificacao + ' - ' + self.armamento.modelo + ' - '
                + self.armamento.nr_serie + ' - ' + self.data)

armamentos/forms.py
from django.forms import ModelForm
from django import forms
from .models import (Armamento,
                     Alteracao,
                     Atividade,
                     Manutencao)
from quarteis.models import Subunidade


class CreateArmamentoForm(ModelForm):
    class Meta:
        model = Armamento
        exclude = ['subunidade']


class CreateAlteracaoForm(ModelForm):
    class Meta:
        model = Alteracao
        exclude = ['is_active', 'armamento']


class CreateAtividadeForm(ModelForm):
    class Meta:
        model = Atividade
        exclude = ['armamento']


class CreateManutencaoForm(ModelForm):
    class Meta:
        model = Manutencao
        exclude = ['armamento']


class UpdateArmamentoForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(UpdateArmamentoForm, self).__init__(*args, **kwargs)
        unidade = user.pessoa.militar.subunidade.esc_sup
        self.fields['subunidade'].queryset = Subunidade.objects.filter(esc_sup=unidade)

    class Meta:
        model = Armamento
        fields = '__all__'

armamentos/views.py
from django.shortcuts import (render,
                              reverse,
                              redirect)
from django.views.generic import (TemplateView,
                                  FormView,
                                  UpdateView,
                                  DetailView,
                                  CreateView,
                                  ListView)
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *
from quarteis.models import *


class HomepageLog(LoginRequiredMixin, TemplateView):
    template_name = "homepagelog.html"


class ReadArmamento(LoginRequiredMixin, ListView):
    template_name = "readarmamento.html"
    model = Armamento

    def get_queryset(self):
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        return Armamento.objects.filter(subunidade__esc_sup=unidade).order_by("situacao")

    def get_context_data(self, **kwargs):
        context = super(ReadArmamento, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        subunidades = Subunidade.objects.filter(esc_sup=unidade)
        fz_total_un = Armamento.objects.filter(subunidade__esc_sup=unidade).filter(classificacao="Fuzil 7,62mm").count()
        pst_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                       .filter(classificacao="Pistola 9mm").count())
        esp_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                       .filter(classificacao="Espingarda 12").count())
        fz_disp_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                       .filter(classificacao="Fuzil 7,62mm").filter(situacao="Disponível").count())
        pst_disp_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                        .filter(classificacao="Pistola 9mm").filter(situacao="Disponível").count())
        esp_disp_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                        .filter(classificacao="Espingarda 12").filter(situacao="Disponível").count())
        fz_ind_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                            .filter(classificacao="Fuzil 7,62mm").filter(situacao="Indisponível").count())
        pst_ind_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                             .filter(classificacao="Pistola 9mm").filter(situacao="Indisponível").count())
        esp_ind_total_un = (Armamento.objects.filter(subunidade__esc_sup=unidade)
                             .filter(classificacao="Espingarda 12").filter(situacao="Indisponível").count())
        context["subunidades"] = subunidades
        context["fz_total_un"] = fz_total_un
        context["fz_disp_total_un"] = fz_disp_total_un
        context["fz_ind_total_un"] = fz_ind_total_un
        context["pst_total_un"] = pst_total_un
        context["pst_disp_total_un"] = pst_disp_total_un
        context["pst_ind_total_un"] = pst_ind_total_un
        context["esp_total_un"] = esp_total_un
        context["esp_disp_total_un"] = esp_disp_total_un
        context["esp_ind_total_un"] = esp_ind_total_un
        return context


class CreateArmamento(LoginRequiredMixin, CreateView):
    template_name = "createarmamento.html"
    form_class = CreateArmamentoForm

    def form_valid(self, form):
        subunidade_logada = self.request.user.pessoa.militar.subunidade
        form.instance.subunidade = subunidade_logada
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('armamentos:readarmamento')


class UpdateArmamento(LoginRequiredMixin, UpdateView):
    template_name = "updatearmamento.html"
    model = Armamento
    form_class = UpdateArmamentoForm

    def get_form_kwargs(self):
        kwargs = super(UpdateArmamento, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('armamentos:readarmamento')


class DetailArmamento(LoginRequiredMixin, DetailView):
    template_name = "detailarmamento.html"
    model = Armamento


def recolhimento_armamento(request, id):
    armamento = Armamento.objects.get(id=id)
    armamento.situacao = "Recolhido"
    armamento.save()
    return redirect('armamentos:readarmamento')


def disponibilizar_armamento(request, id):
    alteracao = Alteracao.objects.get(id=id)
    alteracao.is_active = False
    alteracao.situacao = "Disponível"
    alteracao.save()
    id_armt = alteracao.armamento.id
    armt = Armamento.objects.get(id=id_armt)
    bad = armt.alteracao.all().exclude(situacao="Disponível").filter(is_active=True)
    if not bad:
        armt.situacao = "Disponível"
        armt.save()
    return redirect('armamentos:detailarmamento', id_armt)


def descarga_armamento(request, id):
    armamento = Armamento.objects.get(id=id)
    armamento.situacao = "Descarregado"
    armamento.save()
    return redirect('armamentos:readarmamento')


class CreateAlteracao(LoginRequiredMixin, CreateView):
    template_name = "createalteracao.html"
    form_class = CreateAlteracaoForm

    def form_valid(self, form):
        id = int(self.request.GET.get("armamento_id"))
        armamento = Armamento.objects.get(id=id)
        form.instance.armamento = armamento
        if form.instance.is_active and (form.instance.situacao != armamento.situacao):
            armamento.situacao = form.instance.situacao
            armamento.save()
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('armamentos:readarmamento')


class CreateAtividade(LoginRequiredMixin, CreateView):
    template_name = "createatividade.html"
    model = Atividade
    form_class = CreateAtividadeForm

    def form_valid(self, form):
        id = int(self.request.GET.get("armamento_id"))
        armamento = Armamento.objects.get(id=id)
        form.instance.armamento = armamento
        armamento.qtde_tiros += form.instance.disparos
        form.save()
        armamento.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('armamentos:readarmamento')


class CreateManutencao(LoginRequiredMixin, CreateView):
    template_name = "createmanutencao.html"
    form_class = CreateManutencaoForm

    def form_valid(self, form):
        id = int(self.request.GET.get("armamento_id"))
        armamento = Armamento.objects.get(id=id)
        form.instance.armamento = armamento
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('armamentos:readarmamento')

armamentos/templates/createalteracao.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Cadastrar Altereção
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Cadastrar Alteração</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Cadastre uma nova alteração</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Cadastrar</button>
                <a href="{% url 'armamentos:readarmamento' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
{% include 'footer.html' %}
{% endblock %}

armamentos/templates/createarmamento.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Cadastrar Armamento
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Cadastrar Armamento</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Cadastre um novo armamento</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Cadastrar</button>
                <a href="{% url 'armamentos:readarmamento' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
{% include 'footer.html' %}
{% endblock %}

armamentos/templates/createatividade.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Cadastrar Atividade
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Cadastrar Atividade</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Cadastre uma nova atividade</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Cadastrar</button>
                <a href="{% url 'armamentos:readarmamento' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
{% include 'footer.html' %}
{% endblock %}

armamentos/templates/createmanutencao.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Cadastrar Manutenção
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Cadastrar Manutenção</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Cadastre uma nova manutenção</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Cadastrar</button>
                <a href="{% url 'armamentos:readarmamento' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
{% include 'footer.html' %}
{% endblock %}

armamentos/templates/readarmamento.html
{% extends 'base.html' %}
{% block titulo %}
Armamentos
{% endblock %}
{% block head %}
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-12 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <div>
                    <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                        <span class="fs-4">Resumo Armamentos - {{ request.user.pessoa.militar.subunidade.esc_sup.abreviatura }}</span>
                    </a>
                </div>

            </header>

            <table class="text-center table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th colspan="3">Fuzil 7,62mm</th>
                        <th colspan="3">Pistola 9mm</th>
                        <th colspan="3">Espingarda 12</th>
                    </tr>
                    <tr>
                        <th scope="col" style="width: 10%">Subunidade</th>
                        <th scope="col" style="width: 10%">Disp</th>
                        <th scope="col" style="width: 10%">Indisp</th>
                        <th scope="col" style="width: 10%">Total</th>
                        <th scope="col" style="width: 10%">Disp</th>
                        <th scope="col" style="width: 10%">Indisp</th>
                        <th scope="col" style="width: 10%">Total</th>
                        <th scope="col" style="width: 10%">Disp</th>
                        <th scope="col" style="width: 10%">Indisp</th>
                        <th scope="col" style="width: 10%">Total</th>
                    </tr>

                </thead>
                <tbody>
                    {% for su in subunidades %}
                        <tr>
                            <th scope="row" style="width: 19%">{{ su.abreviatura }}</th>
                            <td style="width: 9%">{{ su.total_fz_disp }}</td>
                            <td style="width: 9%">{{ su.total_fz_indisp }}</td>
                            <td style="width: 9%">{{ su.total_fz }}</td>
                            <td style="width: 9%">{{ su.total_pst_disp }}</td>
                            <td style="width: 9%">{{ su.total_pst_indisp }}</td>
                            <td style="width: 9%">{{ su.total_pst }}</td>
                            <td style="width: 9%">{{ su.total_esp_disp }}</td>
                            <td style="width: 9%">{{ su.total_esp_indisp }}</td>
                            <td style="width: 9%">{{ su.total_esp }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th scope="row" style="width: 10%">Total {{ request.user.pessoa.militar.subunidade.esc_sup.abreviatura }}</th>
                        <td style="width: 10%">{{ fz_disp_total_un }}</td>
                        <td style="width: 10%">{{ fz_ind_total_un }}</td>
                        <td style="width: 10%">{{ fz_total_un }}</td>
                        <td style="width: 10%">{{ pst_disp_total_un }}</td>
                        <td style="width: 10%">{{ pst_ind_total_un }}</td>
                        <td style="width: 10%">{{ pst_total_un }}</td>
                        <td style="width: 10%">{{ esp_disp_total_un }}</td>
                        <td style="width: 10%">{{ esp_ind_total_un }}</td>
                        <td style="width: 10%">{{ esp_total_un }}</td>
                    </tr>
                </tbody>
            </table>
            <br>
            <br>

            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <div>
                    <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                        <span class="fs-4">Lista de Armamentos - {{ request.user.pessoa.militar.subunidade.esc_sup.abreviatura }}</span>
                    </a>
                </div>

            </header>

            <table class="text-center table table-bordered">
                <div class="text-end">
                    <a href="{% url 'armamentos:createarmamento' %}">
                        <button type="button" class="btn btn-outline-info">Novo</button>
                    </a>
                    <br>
                    <br>
                </div>
                <thead>
                    <tr>
                        <th scope="col">Classificação</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Nr Série</th>
                        <th scope="col">Situação</th>
                        <th scope="col">Subunidade</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for armamento in object_list %}
                    <tr>

                        <td>{{ armamento.classificacao }}</td>
                        <td>{{ armamento.modelo }}</td>
                        <td><a href="{% url 'armamentos:detailarmamento' armamento.id %}">{{ armamento.nr_serie }}</a></td>
                        <td>{{ armamento.situacao }}</td>
                        <td>{{ armamento.subunidade.abreviatura }}</td>
                        <td>
                            <div style="display: flex;">
                                <form action="{% url 'armamentos:createatividade' %}" method="get">
                                    {% csrf_token %}
                                    <fieldset>
                                        <input type="hidden" name="armamento_id" value="{{ armamento.id }}">
                                        <button type="submit" class="btn btn-outline-success"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                title="Registrar atividade">
                                            <i class="bi bi-activity"></i>
                                        </button>
                                    </fieldset>
                                </form>&nbsp
                                <form action="{% url 'armamentos:createmanutencao' %}" method="get">
                                    {% csrf_token %}
                                    <fieldset>
                                        <input type="hidden" name="armamento_id" value="{{ armamento.id }}">
                                        <button type="submit" class="btn btn-outline-success"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                title="Registrar manutenção">
                                            <i class="bi bi-tools"></i>
                                        </button>
                                    </fieldset>
                                </form>&nbsp
                                <a href="{% url 'armamentos:updatearmamento' armamento.id %}">
                                    <button type="button" class="btn btn-outline-warning"
                                            data-toggle="tooltip" data-placement="top" title="Alterar dados">
                                        <i class="bi bi-arrow-clockwise"></i>
                                    </button>
                                </a>&nbsp
                                <form action="{% url 'armamentos:createalteracao' %}" method="get">
                                    {% csrf_token %}
                                    <fieldset>
                                        <input type="hidden" name="armamento_id" value="{{ armamento.id }}">
                                        <button type="submit" class="btn btn-outline-warning"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                title="Registrar alteração">
                                            <i class="bi bi-pencil-square"></i>
                                        </button>
                                    </fieldset>
                                </form>&nbsp
                                <a href="{% url 'armamentos:recolhimento_armamento' armamento.id %}">
                                    <button type="button" class="btn btn-outline-danger"
                                            data-toggle="tooltip" data-placement="top" title="Registrar recolhimento">
                                        <i class="bi bi-gear"></i>
                                    </button>
                                </a>&nbsp
                                <a href="{% url 'armamentos:descarga_armamento' armamento.id %}">
                                    <button type="button" class="btn btn-outline-danger"
                                            data-toggle="tooltip" data-placement="top" title="Registrar descarga">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                </a>&nbsp
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

armamentos/templates/updatearmamento.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Atualizar Armamento
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarlog.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-8 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                    <span class="fs-4">Atualizar Armamento</span>
                </a>
            </header>
            <form method="post" class="form-signin text-center">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Atualize Armamento</h1>
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Atualizar</button>
                <a href="{% url 'armamentos:readarmamento' %}"><button type="button" class="btn btn-outline-warning">
                    Voltar</button></a>
            </form>
        </div>
    </div>
{% include 'footer.html' %}
{% endblock %}