municoes/urls.py
from django.urls import path
from .views import *

app_name = 'municoes'

urlpatterns = [
    path('logistica/readmunicao/', ReadMunicao.as_view(), name='readmunicao'),
    path('logistica/createmunicao/', CreateMunicao.as_view(), name='createmunicao'),
    path('logistica/updatemunicao/<int:pk>', UpdateMunicao.as_view(), name='updatemunicao'),
    path('logistica/createconsuno/', CreateConsumo.as_view(), name='createconsumo'),
]

operacoes/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'operacoes'

urlpatterns = [
    path('homeop/', ReadOperacoes.as_view(), name='homepageop'),
    path('pessoal/', ReadPessoal.as_view(), name='readpessoal'),
    path('<int:pk>/geral', ReadGeral.as_view(), name='readgeral'),
    path('planoembarquegeral/', ReadPlanoEmbarqueGeral.as_view(), name='readplanoembarquegeral'),
    path('<int:pk>/planoembarque', ReadPlanoEmbarque.as_view(), name='readplanoembarque'),
    path('<int:pk>/planoembarquevtr', ReadPlanoEmbarqueVtr.as_view(), name='readplanoembarquevtr'),
    path('<int:pk>/armtop', ReadArmtOp.as_view(), name='readarmtop'),
    path('<int:pk>/updatearma', UpdateArma.as_view(), name='updatearma'),
    path('<int:pk>/updatepassageiro', UpdatePassageiro.as_view(), name='updatepassageiro'),
    path('<int:pk>/updatemotorista', UpdateMotorista.as_view(), name='updatemotorista'),
    path('<int:pk>/updatechefe', UpdateChefe.as_view(), name='updatechefe'),
    path('<int:pk>/updateplembvtr', UpdatePlEmbVtr.as_view(), name='updateplembvtr'),
    path('<int:pk>/updateplanoembarque', UpdatePlanoEmbarque.as_view(), name='updateplanoembarque'),
    path('createoperacao/', CreateOperacao.as_view(), name='createoperacao'),
    path('createplanoembarque/', CreatePlanoEmbarque.as_view(), name='createplanoembarque'),
    path('createplembvtr/', CreatePlEmbVtr.as_view(), name='createplembvtr'),
    path('createorgao/', CreateOrgao.as_view(), name='createorgao'),
    path('createoperacional/', CreateOperacional.as_view(), name='createoperacional'),
    path('createchefe/', CreateChVtr.as_view(), name='createchefevtr'),
    path('createmotorista/', CreateMotoVtr.as_view(), name='createmotovtr'),
    path('createpassageiro/', CreatePassageiro.as_view(), name='createpassagvtr'),
    path('download-plemb-pdf/', PlanoEmbarquePdf.as_view(), name='download_plemb_pdf'),
    path('download-manemb-pdf/', ManifestoEmbarquePdf.as_view(), name='download_manemb_pdf'),
    path('download-armt-pdf/', ArmamentoPdf.as_view(), name='download_armt_pdf'),
    path('download-participantes-pdf/', ParticipantesPdf.as_view(), name='download_participantes_pdf'),
    re_path(r'^create_fz/(?P<id>\d+)$', create_fz, name='create_fz'),
    re_path(r'^create_pst/(?P<id>\d+)$', create_pst, name='create_pst'),
    re_path(r'^delete_orgao/(?P<id>\d+)/$', delete_orgao, name='delete_orgao'),
    re_path(r'^delete_operacional/(?P<id>\d+)/$', delete_operacional, name='delete_operacional'),
    re_path(r'^delete_chefe/(?P<id>\d+)/$', delete_chefe, name='delete_chefe'),
    re_path(r'^delete_motorista/(?P<id>\d+)/$', delete_motorista, name='delete_motorista'),
    re_path(r'^delete_passageiro/(?P<id>\d+)/$', delete_passageiro, name='delete_passageiro'),
    re_path(r'^delete_armt/(?P<id>\d+)/$', delete_armt, name='delete_armt'),
    re_path(r'^delete_plano_embarque_vtr/(?P<id>\d+)/$', delete_plano_embarque_vtr, name='delete_plano_embarque_vtr'),
    re_path(r'^delete_plano_embarque_/(?P<id>\d+)/$', delete_plano_embarque, name='delete_plano_embarque'),
    re_path(r'^update_mun_armt/(?P<id>\d+)/$', update_mun_armt, name='update_mun_armt'),
]

sisgestao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    #path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    #path('militares/', include('militares.urls', namespace='militares')),
    #path('contatos/', include('contatos.urls', namespace='contatos')),
    #path('documentos/', include('documentos.urls', namespace='documentos')),
    #path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    #path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('operacoes/', include('operacoes.urls', namespace='operacoes')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('municoes/', include('municoes.urls', namespace='municoes')),
    path('armamentos/', include('armamentos.urls', namespace='armamentos')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operacoes/views.py
from django.shortcuts import (render,
                              reverse,
                              redirect)
from django.views.generic import (TemplateView,
                                  FormView,
                                  UpdateView,
                                  DetailView,
                                  CreateView,
                                  ListView,
                                  View)
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa
import io


class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Error Rendering PDF", status=400)


class ReadOperacoes(LoginRequiredMixin, ListView):
    template_name = "readoperacoes.html"
    model = Atividade

    def get_queryset(self):
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        return Atividade.objects.filter(unidade=unidade).order_by("data_inicio")

    def get_context_data(self, **kwargs):
        context = super(ReadOperacoes, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        operacoes = Atividade.objects.filter(unidade=unidade, is_active=True)
        context['operacoes'] = operacoes
        return context


class ReadGeral(LoginRequiredMixin, DetailView):
    template_name = "readgeral.html"
    model = Atividade

    def get_queryset(self):
        return Atividade.objects.order_by("orgao__subunidade")

    def get_context_data(self, **kwargs):
        context = super(ReadGeral, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        operacoes = Atividade.objects.filter(unidade=unidade, is_active=True)
        context['operacoes'] = operacoes
        efetivo_total = 0
        for orgao in self.object.orgao.all():
            efetivo_total += orgao.operacional.count()
        context['efetivo_total'] = efetivo_total
        return context


class ReadPlanoEmbarque(LoginRequiredMixin, DetailView):
    template_name = "readplanoembarque.html"
    model = PlanoEmbarque

    def get_context_data(self, **kwargs):
        context = super(ReadPlanoEmbarque, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        operacoes = Atividade.objects.filter(unidade=unidade, is_active=True)
        context['operacoes'] = operacoes
        passageiros = 0
        for mil in self.object.plano_embarque_vtr.all():
            passageiros += mil.passageiro.count()
        context['passageiros'] = passageiros
        return context


class ReadPlanoEmbarqueVtr(LoginRequiredMixin, DetailView):
    template_name = "readplanoembarquevtr.html"
    model = PlanoEmbarqueViatura

    def get_context_data(self, **kwargs):
        context = super(ReadPlanoEmbarqueVtr, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        operacoes = Atividade.objects.filter(unidade=unidade, is_active=True)
        context['operacoes'] = operacoes
        return context


class ReadArmtOp(LoginRequiredMixin, DetailView):
    template_name = "readarmtop.html"
    model = Atividade

    def get_context_data(self, **kwargs):
        context = super(ReadArmtOp, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        operacoes = Atividade.objects.filter(unidade=unidade, is_active=True)
        context['operacoes'] = operacoes
        id = self.object.id
        atividade = Atividade.objects.get(id=id)
        fuzis = Arma.objects.fuzil().filter(operacional__orgao__atividade=atividade)
        pistolas = Arma.objects.pistola().filter(operacional__orgao__atividade=atividade)
        total_fz = fuzis.count()
        total_pst = pistolas.count()
        qtde_mun_fz = 0
        qtde_mun_pst = 0
        for fuzil in fuzis:
            qtde_mun_fz += fuzil.qtde_mun
        for pistola in pistolas:
            qtde_mun_pst += pistola.qtde_mun
        context['total_fz'] = total_fz
        context['total_pst'] = total_pst
        context['qtde_mun_fz'] = qtde_mun_fz
        context['qtde_mun_pst'] = qtde_mun_pst
        return context


class ReadPessoal(LoginRequiredMixin, ListView):
    template_name = "readpessoal.html"
    model = Operacional

    def get_queryset(self):
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        atividade = Atividade.objects.get(unidade=unidade, is_active=True)
        return Operacional.objects.filter(orgao__atividade=atividade).order_by("militar__posto_grad")

    def get_context_data(self, **kwargs):
        context = super(ReadPessoal, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        operacoes = Atividade.objects.filter(unidade=unidade, is_active=True)
        atividade = Atividade.objects.get(unidade=unidade, is_active=True)
        oficiais = 0
        st_sgt = 0
        cb_sd = 0
        cel = 0
        tc = 0
        maj = 0
        cap = 0
        ten1 = 0
        ten2 = 0
        asp = 0
        st = 0
        sgt1 = 0
        sgt2 = 0
        sgt3 = 0
        cb = 0
        sd_nb = 0
        sd_ev = 0
        for orgao in atividade.orgao.all():
            oficiais += orgao.operacional.all().oficiais().count()
            st_sgt += orgao.operacional.all().st_sgt().count()
            cb_sd += orgao.operacional.all().cb_sd().count()
            cel += orgao.operacional.all().cel().count()
            tc += orgao.operacional.all().tc().count()
            maj += orgao.operacional.all().maj().count()
            cap += orgao.operacional.all().cap().count()
            ten1 += orgao.operacional.all().um_ten().count()
            ten2 += orgao.operacional.all().dois_ten().count()
            asp += orgao.operacional.all().asp().count()
            st += orgao.operacional.all().st().count()
            sgt1 += orgao.operacional.all().um_sgt().count()
            sgt2 += orgao.operacional.all().dois_sgt().count()
            sgt3 += orgao.operacional.all().tres_sgt().count()
            cb += orgao.operacional.all().cb().count()
            sd_nb += orgao.operacional.all().sd_nb().count()
            sd_ev += orgao.operacional.all().sd_ev().count()
        context['operacoes'] = operacoes
        context['oficiais'] = oficiais
        context['st_sgt'] = st_sgt
        context['cb_sd'] = cb_sd
        context['cel'] = cel
        context['tc'] = tc
        context['maj'] = maj
        context['cap'] = cap
        context['ten1'] = ten1
        context['ten2'] = ten2
        context['asp'] = asp
        context['st'] = st
        context['sgt1'] = sgt1
        context['sgt2'] = sgt2
        context['sgt3'] = sgt3
        context['cb'] = cb
        context['sd_nb'] = sd_nb
        context['sd_ev'] = sd_ev
        return context


class ReadPlanoEmbarqueGeral(LoginRequiredMixin, ListView):
    template_name = "readplanoembarquegeral.html"
    model = PlanoEmbarque

    def dispatch(self, request, *args, **kwargs):
        if self.request.GET.get('pk_atv'):
            self.request.session['pt_atv'] = self.request.GET.get('pk_atv')
        return super(ReadPlanoEmbarqueGeral, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        pk_atv = self.request.session['pt_atv']
        return PlanoEmbarque.objects.filter(atividade__id=pk_atv, atividade__unidade=unidade, is_active=True)

    def get_context_data(self, **kwargs):
        context = super(ReadPlanoEmbarqueGeral, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoa.militar.subunidade.esc_sup
        operacoes = Atividade.objects.filter(unidade=unidade, is_active=True)
        context['operacoes'] = operacoes
        return context


class CreateOperacao(LoginRequiredMixin, CreateView):
    template_name = "createoperacao.html"
    form_class = CreateOperacaoForm

    def form_valid(self, form):
        unidade_logada = self.request.user.pessoa.militar.subunidade.esc_sup
        form.instance.unidade = unidade_logada
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('operacoes:homepageop')


class CreatePlanoEmbarque(LoginRequiredMixin, CreateView):
    template_name = "createplanoembarque.html"
    form_class = CreatePlanoEmbarqueForm

    def form_valid(self, form):
        unidade_logada = self.request.user.pessoa.militar.subunidade.esc_sup
        atividade = Atividade.objects.get(unidade=unidade_logada, is_active=True)
        form.instance.atividade = atividade
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('operacoes:readplanoembarquegeral')


class CreatePlEmbVtr(LoginRequiredMixin, CreateView):
    template_name = "createplembvtr.html"
    form_class = CreatePlEmbVtrForm

    def get_form_kwargs(self):
        kwargs = super(CreatePlEmbVtr, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        id_plemb = int(self.request.GET.get('id_plemb'))
        plano_embarque = PlanoEmbarque.objects.get(id=id_plemb)
        form.instance.plano_embarque = plano_embarque

operacoes/templates/readarmtop.html
{% extends 'base.html' %}
{% block titulo %}
Op {{ object.nome }}
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarop.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-12 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <div class="row">
                    <div class="col-11">
                        <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                            <span class="fs-4">Armamentos - Operação {{ object.nome.upper }} - {{ request.user.pessoa.militar.subunidade.esc_sup.abreviatura }}</span>
                        </a>
                    </div>
                    <div class="col-1">
                        <form method="get" action="{% url 'operacoes:download_armt_pdf' %}">
                            {% csrf_token %}
                            <fieldset>
                                <input type="hidden" name="pk_atv" value="{{ object.id }}">
                                <button type="submit" class="btn btn-outline-success"><i class="bi bi-file-earmark-arrow-down-fill"></i></button>
                            </fieldset>
                        </form>
                    </div>
                </div>
                <div>

                </div>

            </header>
            <table class="text-center table table-bordered">
                <thead>
                    <tr>
                        <th>Órgão</th>
                        <th>Subunidade</th>
                        <th>Posto/Grad</th>
                        <th>Nome de Guerra</th>
                        <th>Fuzil</th>
                        <th>Mun Fz</th>
                        <th>Nr Fz</th>
                        <th>Pistola</th>
                        <th>Mun Pst</th>
                        <th>Nr Pst</th>
                    </tr>
                </thead>
                <tbody>
                    {% for orgao in object.orgao.all %}
                        {% if orgao.operacional.all %}
                            <tr>
                                <td rowspan="{{ orgao.operacional.count }}" class="text-center align-middle">{{ orgao.nome }}</td>
                                <td rowspan="{{ orgao.operacional.count }}" class="text-center align-middle">{{ orgao.subunidade.abreviatura }}</td>
                            {% for operacional in orgao.operacional.all %}
                                <td>{{ operacional.militar.posto_grad }}</td>
                                <td>{{ operacional.militar.nome_guerra.upper }}</td>
                                {% if operacional.arma.all.fuzil %}
                                    <td><a href="{% url 'operacoes:delete_armt' operacional.arma.all.fuzil_get.id %}"><i class="bi bi-check2-circle"></i></a></td>
                                    {% for fz in operacional.arma.all.fuzil %}
                                        {% if fz.municao %}
                                <td><a href="{% url 'operacoes:update_mun_armt' operacional.arma.all.fuzil_get.id %}">{{ fz.qtde_mun }}</a></td>
                                        {% else %}
                                            <td><a href="{% url 'operacoes:update_mun_armt' operacional.arma.all.fuzil_get.id %}"><i class="bi bi-x-circle-fill"></i></a></td>
                                        {% endif %}
                                        {% if fz.armamento %}
                                            <td>{{ fz.armamento.nr_serie }}</td>
                                        {% else %}
                                            <td><a href="{% url 'operacoes:updatearma' operacional.arma.fuzil_get.id %}" class="btn btn-outline-warning">Definir</a></td>
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <td><a href="{% url 'operacoes:create_fz' operacional.id %}"><i class="bi bi-x-circle-fill danger"></i></a></td>
                                    <td>Desarmado</td>
                                    <td>Desarmado</td>
                                {% endif %}
                                {% if operacional.arma.all.pistola %}
                                    <td><a href="{% url 'operacoes:delete_armt' operacional.arma.all.pistola_get.id %}"><i class="bi bi-check2-circle"></i></a></td>
                                    {% for pst in operacional.arma.all.pistola %}
                                        {% if pst.municao %}
                                <td><a href="{% url 'operacoes:update_mun_armt' operacional.arma.all.pistola_get.id %}">{{ pst.qtde_mun }}</a></td>
                                        {% else %}
                                            <td><a href="{% url 'operacoes:update_mun_armt' operacional.arma.all.pistola_get.id %}"><i class="bi bi-x-circle-fill"></i></a></td>
                                        {% endif %}
                                        {% if pst.armamento %}
                                            <td>{{ pst.armamento.nr_serie }}</td>
                                        {% else %}
                                            <td><a href="{% url 'operacoes:updatearma' operacional.arma.pistola_get.id %}" class="btn btn-outline-warning">Definir</a></td>
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <td><a href="{% url 'operacoes:create_pst' operacional.id %}"><i class="bi bi-x-circle-fill danger"></i></a></td>
                                    <td>Desarmado</td>
                                    <td>Desarmado</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                    <tr>
                        <td colspan="3"><b>Quantidade Total Fuzis</b></td>
                        <td colspan="2">{{ total_fz }}</td>
                        <td colspan="3"><b>Quantidade Total Pistolas</b></td>
                        <td colspan="2">{{ total_pst }}</td>
                    </tr>
                    <tr>
                        <td colspan="3"><b>Quantidade Munições Fuzil</b></td>
                        <td colspan="2">{{ qtde_mun_fz }}</td>
                        <td colspan="3"><b>Quantidade Munições Pistola</b></td>
                        <td colspan="2">{{ qtde_mun_pst }}</td>
                    </tr>
                </tbody>
            </table>
            <br>
            <br>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

operacoes/templates/readplanoembarque.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}
Op {{ object.atividade.nome }}
{% endblock %}
{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarop.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-12 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <div>
                    <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                        <span class="fs-4">Plano de Embarque - Operação {{ object.atividade.nome.upper }} - {{ request.user.pessoa.militar.subunidade.esc_sup.abreviatura }}</span>
                    </a>
                </div>
            </header>
            <div class="row justify-content-between">
                <div class="col-4">
                    <form method="get" action="{% url 'operacoes:download_plemb_pdf' %}">
                        {% csrf_token %}
                        <fieldset>
                            <input type="hidden" name="id_ple" value="{{ object.id }}">
                            <button type="submit" class="btn btn-outline-success"><i class="bi bi-file-earmark-arrow-down-fill"></i></button>
                        </fieldset>
                    </form>
                </div>
                <div class="col-4">
                    <form method="get" action="{% url 'operacoes:createplembvtr' %}">
                    {% csrf_token %}
                        <fieldset>
                            <input type="hidden" name="id_plemb" value="{{ object.id }}">
                            <button type="submit" class="btn btn-outline-info">Nova Vtr</button>
                        </fieldset>
                    </form>
                </div>
            </div>
            <br>
            <br>
            <table class="text-center table table-bordered">
                <thead>
                    <tr>
                        <th>Ord</th>
                        <th>Nr Patr</th>
                        <th>Tipo</th>
                        <th>Dslc</th>
                        <th>Motorista</th>
                        <th>Chefe</th>
                        <th>Ef</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for vtr in object.plano_embarque_vtr.all %}
                        <tr>
                            <td>{{ vtr.nr_vtr }}</td>
                            <td><a href="{% url 'operacoes:readplanoembarquevtr' vtr.id %}">{{ vtr.viatura.patrimonio }}</a></td>
                            <td>{{ vtr.viatura.dados_tecnicos.classificacao }}</td>
                            <td>{{ vtr.final_dslc }}</td>
                            <td>{{ vtr.motorista.passageiro.operacional.militar.nome_guerra.upper }}</td>
                            <td>{{ vtr.chefe.passageiro.operacional.militar.nome_guerra.upper }}</td>
                            <td>{{ vtr.passageiro.count }}</td>
                            <td>
                                <div class="row">
                                    <div class="col">
                                        <a href="{% url 'operacoes:updateplembvtr' vtr.id %}">
                                            <button type="submit" class="btn btn-outline-warning"><i class="bi bi-arrow-clockwise"></i></button>
                                        </a>
                                    </div>
                                    <div class="col">
                                        <a href="{% url 'operacoes:delete_plano_embarque_vtr' vtr.id %}">
                                            <button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash"></i></button>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="2"><b>Total de Viaturas</b></td>
                        <td colspan="2">{{ object.plano_embarque_vtr.count }}</td>
                        <td colspan="2"><b>Efetivo Total</b></td>
                        <td colspan="2">{{ passageiros }}</td>
                    </tr>
                </tbody>
            </table>
            <br>
            <br>
            <div class="col-9">
                <div class="col-lg-8 mx-auto p-4 py-md-5">
                    <form method="get" action="{% url 'operacoes:readplanoembarquegeral' %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <fieldset>
                            <input type="hidden" name="pk_atv" value="{{ object.atividade.id }}">
                            <button type="submit" class="btn btn-outline-warning">Voltar</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

operacoes/templates/readplanoembarquegeral.html
{% extends 'base.html' %}
{% block titulo %}
Plano de Embarque
{% endblock %}

{% block main %}
{% include 'topbar.html' %}
<div class="row">
    <div class="col-3">
        {% include 'sidebarop.html' %}
    </div>
    <div class="col-9">
        <div class="col-lg-12 mx-auto p-4 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <div>
                    <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                        <span class="fs-4">PLANO DE EMBARQUE - Operação {{ object_list.first.atividade.nome.upper }} - {{ request.user.pessoa.militar.subunidade.esc_sup.abreviatura }}</span>
                    </a>
                </div>
            </header>
            <div class="text-end">
                <a href="{% url 'operacoes:createplanoembarque' %}">
                    <button type="button" class="btn btn-outline-info">Nova</button>
                </a>
                <br>
                <br>
            </div>
            <table class="text-center table table-bordered">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Início</th>
                        <th>Qtde Vtr</th>
                        <th>Efetivo</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for plano in object_list %}
                        <tr>
                            <td><a href="{% url 'operacoes:readplanoembarque' plano.id %}">{{ plano.comboio }}</a></td>
                            <td>{{ plano.inicio }}</td>
                            <td>{{ plano.plano_embarque_vtr.count }}</td>
                            <td>{{ plano.efetivo }}</td>
                            <td>
                                <div class="row">
                                    <div class="col">
                                        <a href="{% url 'operacoes:updateplanoembarque' plano.id %}">
                                            <button type="submit" class="btn btn-outline-warning"><i class="bi bi-arrow-clockwise"></i></button>
                                        </a>
                                    </div>
                                    <div class="col">
                                        <a href="{% url 'operacoes:delete_plano_embarque' plano.id %}">
                                            <button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash"></i></button>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <br>
            <br>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}